# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 5 # it will paginate after this number
language: 'en-GB'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
url: "https://yawnofthedad.blog"
baseurl: "/"
# Website info
title: Yawn of the Dad
description: A new dad's blog about hopefully avoiding becoming one of the living dead. Er, dads.

# Social info
navigation: True # show the navbar links
subscribers: False
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: mattpointblank # replace by your username

# Disqus
disqus: False


# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      current: post
      layout: post
      navigation: true
      class: post-template
      subclass: 'post'
      author: matt



# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - "*.sh"
  - .git*
